### ISSUE TITLE
Inital commands

### ISSUE THREAD

**Issue by Salinatorimperator** [yardstick17/image_text_reader#5]
Hey man, thank you for the repository. Looks really good. 

Could you add the initial commands to the readme file? I having an issue with the output and I think it is because I miss some step in the installation. 

What I am gettting:
 from this command: `PYTHONPATH='/usr/bin/python3' python3 read_image.py read_text_from_local_image -f images/sample_image.jpg`

Something like this:

```
[2019-06-22 20:45:35,880] INFO : Processing image for text Extraction
[2019-06-22 20:45:36,043] INFO : Removing noise and smoothening image
[2019-06-22 20:45:36,108] INFO : Reading the text inside the contour plotted


- 'souihpu! c09

'19?!
94-5966-494


harp lager.


6.75


```
Do you have any hint about the reason behind this?

Thanks!

**Comment by yardstick17** [comment]
Hey,

I think it went fine. 

**What is the issue?**
The output from the reader doesn't look good.

**Why?**
OCR doesn't always perfect results for all images. It works fine for some set of images with text. In your case, I would suggest to try with other images having text more clear and in the standard format and see what is the result.
